name: flutter_app_sections
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.3
  launch_review: ^2.0.0
  flutter_webview_plugin: ^0.3.5
#  webview_flutter: ^0.3.2
  flutter_full_pdf_viewer: ^1.0.4
  flutter_pdfview: ^1.0.0+4
  path_provider: any
#  flutter_pdf_viewer: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: images/iosIcon.png
  image_path_android: images/appIconRound.png
  adaptive_icon_background: images/androidIconBackground.png
  adaptive_icon_foreground: images/androidIconForeground.png



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  plugin:
#    androidPackage: com.alveliu.flutterfullpdfviewer
#    pluginClass: FlutterFullPdfViewerPlugin

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/esteem.png
  - images/Blue.jpg
  - images/comb_electrode.jpg
  - images/fa_logo@3x.png
  - images/fa_logo.png
  - images/Avazzia_Icon.png
  - images/QRS_Icon.png
  - images/Gut_Icon.png
  - images/LW1.png
  - images/LW2.png
  - images/LW3.png
  - images/LW4.png
  - images/SR.png
  - images/Carpal_Neck.jpg
  - images/gutstep5.png
  - images/gutstep6.png
  - images/gutstep7.png
  - images/gutstep8.png
  - images/gutcheck1.png
  - images/gutcheck2.png
  - images/gutcheck3.png
  - images/gutcheck12.png
  - images/gutcheck13.png
  - images/gutcheck14.png
  - images/sciatica.png
  - images/plantar1.png
  - images/plantar2.png
  - images/elbow1.png
  - images/elbow2.png
  - images/elbow3.png
  - images/mdlivelogo.png
  - images/fachealthlogo.png
  - images/falogo.png
  - images/QRSBtn.png
  - images/GutCheck.png
  - images/AvazziaBtn.png
  - images/FullFALogo.png
  - images/listbackground.png
  - images/button.png
  - images/AvazziaBackground.png
  - images/QRSBackground.png
  - images/GutCheckBackground.png
  - images/MDliveTextLogo.png
  - images/FAlogoBackground.png
  - pdfs/essentialOils.pdf
  - pdfs/clinicallyProtocols.pdf
  - pdfs/companyOverview.pdf
  - pdfs/essentialOils.pdf
  - pdfs/QRSproductOverview.pdf
  - pdfs/recommendationReport.pdf
  - pdfs/sampleReport.pdf
  - pdfs/scarPresentation.pdf
  - pdfs/whitePaperPemf.pdf
  - pdfs/ezziliftPresentation.pdf
  - images/androidIconBackground.png
  - images/androidIconForeground.png
  - images/iosIcon.png
  - appIconRound.png
  - images/coreBodyImg1.png
  - images/coreBodyImg2.png
  - images/sixPoint.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
